spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${db.url:jdbc:mariadb://localhost:3306/ex}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${db.username:ryu}
    password: ${db.password:0404}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: com.ekayworks.ex.config.MyMariaDBDialect
    show-sql: true
#    devtools:
#      livereload:
#        enabled: true
    thymeleaf:
      cache: false
      encoding: UTF-8
server:
  port: 8080
  tomcat:
    max-http-form-post-size: 100MB